language: c
sudo: false

cache:
    directories:
    - $HOME/.stack

before_install:
- bash .ci/unpack.sh
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack setup
- stack install pandoc

script:
- stack --no-terminal --skip-ghc-check test

after_success:
- pandoc --standalone -t revealjs presentation/presentation.md -o index.html
- bash .ci/update_pages.sh
